### ISSUE TITLE
Can't find model 'en_core_web_lg'

### ISSUE THREAD

**Issue by satvikmaker** [BrambleXu/news-graph#1]
I am getting the following error when I try to run main.py-

```

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from news_graph import NewsMining
  File "/mnt/d/work/fxpi/futureapi/futureapi-apis-experiment/text-graph/news-graph/news_graph.py", line 8, in <module>
    nlp = spacy.load('en_core_web_lg')
  File "/home/bozzmob/.virtualenvs/dl/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/bozzmob/.virtualenvs/dl/lib/python3.7/site-packages/spacy/util.py", line 139, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

```

Please can you give some thoughts on what packages have to be installed(`requirements.txt`)? I have currently installed spacy.

I am running this on python 3.7.4 version.

**Comment by BrambleXu** [comment]
It's spacy. 
```
nlp = spacy.load('en_core_web_lg')
```
[link](https://spacy.io/models/en#en_core_web_lg)
